# configs/dinov3_convnext_tiny_5ch.yaml

defaults:
  - default.yaml

experiment:
  name: dinov3_convnext_tiny_5ch_val_IoU

data:
  channels: [1, 2, 3, 4, 5]

model:
  name: dinov3_convnext_tiny
  encoder: dinov3_convnext_tiny
  in_channels: 5

training:
  warmup_frozen_epochs: 10

  scheduler:
    enabled: true
    name: cosine # options: cosine, reduce_on_plateau

wandb:
  enabled: true
  group: flair-toy-final-models
  tags:
    - flair
    - segmentation
    - dinov3
    - convnext
    - tiny
    - ssl
