# configs/resnet34_unet_5ch.yaml

defaults:
  - default.yaml

experiment:
  name: resnet34_unet_5ch_val_IoU

data:
  channels: [1, 2, 3, 4, 5]

model:
  name: resnet34_unet
  encoder: resnet34
  in_channels: 5

wandb:
  enabled: true
  group: flair-toy-final-models
  tags:
    - flair
    - segmentation
    - baseline
    - resnet34
    - unet
