# -*- coding: utf-8 -*-
"""calibrate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9N4BM9JSjMgNHs3T5UnbffV7hd8PhH_
"""
import torch
import torch.nn.functional as F
import numpy as np
from tqdm import tqdm
from src.train import sync_class_config
from src.utils import load_config
from src.data import build_dataloaders
from src.models import build_model
from src.evaluate import evaluate_conformal


def collect_calibration_scores(model, loader, num_classes, device):
    """Collect LAC scores (1 - p_true) over all valid pixels in the loader."""
    scores = []
    model.eval()
    with torch.no_grad():
        for batch in tqdm(loader, desc="Calibrating"):
            imgs  = batch["image"].to(device)
            masks = batch["mask"].to(device)

            logits = model(imgs)                          # (B, C, H, W)
            probs  = F.softmax(logits, dim=1)             # (B, C, H, W)

            B, C, H, W = probs.shape
            probs_flat = probs.permute(0, 2, 3, 1).reshape(-1, C)  # (N, C)
            masks_flat = masks.view(-1)                             # (N,)

            # only pixels whose true class is within [0, num_classes)
            valid = (masks_flat >= 0) & (masks_flat < num_classes)
            if valid.sum() == 0:
                continue

            m = masks_flat[valid]
            p = probs_flat[valid]
            p_true = p[torch.arange(len(m)), m]      # probability on true class
            scores.append((1.0 - p_true).cpu().numpy())

    return np.concatenate(scores) if scores else np.array([])

def compute_qhat(scores, alpha):
    """Finite-sample corrected quantile giving (1-alpha) marginal coverage."""
    n = len(scores)
    level = np.ceil((n + 1) * (1 - alpha)) / n
    level = min(level, 1.0)   # clamp — can exceed 1 with very small n
    return float(np.quantile(scores, level))
    
def run_conformal_for_model(model_entry, train_config_base, alpha, device, REPO_ROOT, NUM_CLASSES):
    """Load a model + checkpoint, calibrate, evaluate, return summary dict."""
    cfg = dict(train_config_base)  # shallow copy
    cfg = sync_class_config(load_config(REPO_ROOT / model_entry["config"]))
    cfg["model"]["in_channels"] = model_entry["in_channels"]
    cfg["model"]["num_classes"] = model_entry["num_classes"]
    cfg["data"]["num_classes"]  = model_entry["num_classes"]
    cfg["data"]["channels"]     = list(range(1, model_entry["in_channels"] + 1))

    tl, vl, tel = build_dataloaders(cfg["data"])

    m = build_model(cfg["model"])
    ckpt = torch.load(REPO_ROOT / model_entry["checkpoint"], map_location=device)
    m.load_state_dict(ckpt["model_state_dict"])
    m.to(device).eval()

    sc   = collect_calibration_scores(m, vl, NUM_CLASSES, device)
    qhat = compute_qhat(sc, alpha)
    cov, avg_sz, per_cls_cov, *_ = evaluate_conformal(m, tel, qhat, NUM_CLASSES, device)

    return {"label": model_entry["label"], "q_hat": qhat, "coverage": cov,
            "avg_set_size": avg_sz, "per_class_cov": per_cls_cov}


